files:
  - source: /src/java/fr/paris/lutece/plugins/resource/modules/adminuser/resources/adminuser_messages.properties
    translation: /src/java/fr/paris/lutece/plugins/resource/modules/adminuser/resources/adminuser_messages_%two_letters_code%.properties
  - source: /src/site/xdoc/index.xml
    translation: /src/site/%two_letters_code%/xdoc/index.xml
